#NAME: CHENCHEN
#EMAIL: chenchenstudent@gmail.com
#ID: 004710308

CC = gcc
CFLAGS = -g3 -O0 -Wall -Wextra

default:
	$(CC) $(CFLAGS) -o lab1a lab1a.c

clean:
	rm -rf lab1a *.tar.gz *.o

dist:
	tar -czf lab1a-004710308.tar.gz lab1a.c Makefile README