# NAME: CHEN CHEN
# EMAIL: chenchenstudent@gmail.com
# ID: 004710308
CC = g++
CFLAGS = -g3 -O0 -Wall -Wextra -std=c++0x -lpthread

default:build

build:
	$(CC) lab3b.cpp -o lab3b $(CFLAGS)

dist:
	tar -czvf lab3b-004710308.tar.gz lab3b.cpp lab3b.h README Makefile 

clean:
	rm -f lab3b lab3b-004710308.tar.gz